apiVersion: apps/v1
kind: Deployment
metadata:
  name: insuranceclaim-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: InsuranceClaim
  template:
    metadata:
      labels:
        app: InsuranceClaim
    spec:
      containers:
      - name: insuranceclaimrepos
        image: myregdsconfig.azurecr.io/dockersamplerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: insuranceclaimsn

---
apiVersion: v1
kind: Service
metadata:
  name: insuranceclaim
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: InsuranceClaim